# Entregavel 1

In [106]:
#Entregavel - Processamento de dados

In [107]:
!pip install dfply

Requirement already satisfied: dfply in /usr/local/lib/python3.12/dist-packages (0.3.3)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from dfply) (2.0.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from dfply) (2.2.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->dfply) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->dfply) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->dfply) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->dfply) (1.17.0)

In [108]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Biblioteca dfply
from dfply import *

In [109]:
#Lendo banco de dados

In [110]:
df = pd.read_csv("df_to_filtrado1_2015_2024.csv",sep=",")

##• Verificação de duplicados (Obrigatório)

In [111]:
#DUPLICATAS

In [112]:
#Verificação se existem e quantos são os valores duplicados
df.duplicated().sum()

np.int64(0)

In [113]:
#Verificação de valores duplicados
df.loc[df.duplicated()]

Empty DataFrame
Columns: [Unnamed: 0, TP_NOT, ID_AGRAVO, DT_NOTIFIC, NU_ANO, SG_UF_NOT, ID_MUNICIP, ID_REGIONA, DT_DIAG, ANO_NASC, NU_IDADE_N, CS_SEXO, CS_GESTANT, CS_RACA, CS_ESCOL_N, SG_UF, ID_MN_RESI, ID_RG_RESI, ID_PAIS, NDUPLIC_N, IN_VINCULA, DT_DIGITA, DT_TRANSUS, DT_TRANSDM, DT_TRANSSM, DT_TRANSRM, DT_TRANSRS, DT_TRANSSE, CS_FLXRET, FLXRECEBI, MIGRADO_W, ID_OCUPA_N, TRATAMENTO, INSTITUCIO, RAIOX_TORA, TESTE_TUBE, FORMA, EXTRAPU1_N, EXTRAPU2_N, EXTRAPUL_O, AGRAVAIDS, AGRAVALCOO, AGRAVDIABE, AGRAVDOENC, AGRAVOUTRA, AGRAVOUTDE, BACILOSC_E, BACILOS_E2, BACILOSC_O, CULTURA_ES, CULTURA_OU, HIV, HISTOPATOL, DT_INIC_TR, RIFAMPICIN, ISONIAZIDA, ETAMBUTOL, ESTREPTOMI, PIRAZINAMI, ETIONAMIDA, OUTRAS, OUTRAS_DES, TRAT_SUPER, NU_CONTATO, DOENCA_TRA, SG_UF_AT, ID_MUNIC_A, DT_NOTI_AT, SG_UF_2, ID_MUNIC_2, BACILOSC_1, BACILOSC_2, BACILOSC_3, BACILOSC_4, BACILOSC_5, BACILOSC_6, TRATSUP_AT, DT_MUDANCA, NU_COMU_EX, SITUA_9_M, SITUA_12_M, SITUA_ENCE, DT_ENCERRA, TPUNINOT, POP_LIBER, POP_RUA, POP_SAUDE, POP_IMIG, BENEF_GOV, AGRAVDROGA, AGRAVTABAC, TEST_MOLEC, TEST_SENSI, ANT_RETRO, BAC_APOS_6, TRANSF, UF_TRANSF, MUN_TRANSF, ano]
Index: []

[0 rows x 99 columns]

In [114]:
#Remoção dos Valores duplicados
#df.drop_duplicates(inplace=True)

##• Informações gerais da base (shape, head, info etc.) (Obrigatório)

In [115]:
df.shape

(595, 99)

In [116]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 595 entries, 0 to 594
Data columns (total 99 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  595 non-null    int64
 1   TP_NOT      595 non-null    int64
 2   ID_AGRAVO   595 non-null    object
 3   DT_NOTIFIC  595 non-null    object
 4   NU_ANO      595 non-null    int64
 5   SG_UF_NOT   595 non-null    int64
 6   ID_MUNICIP  595 non-null    int64
 7   ID_REGIONA  119 non-null    float64
 8   DT_DIAG     595 non-null    int64
 9   ANO_NASC    595 non-null    float64
 10  NU_IDADE_N  595 non-null    float64
 11  CS_SEXO     595 non-null    object
 12  CS_GESTANT  595 non-null    float64
 13  CS_RACA     595 non-null    float64
 14  CS_ESCOL_N  581 non-null    float64
 15  SG_UF       595 non-null    int64
 16  ID_MN_RESI  595 non-null    int64
 17  ID_RG_RESI  116 non-null    float64
 18  ID_PAIS     595 non-null    float64
 19  NDUPLIC_N   139 non-null    float64
 20  IN_VINCULA  268 non-null    float64
 21  DT_DIGITA   479 non-null    float64
 22  DT_TRANSUS  18 non-null     float64
 23  DT_TRANSDM  0 non-null      float64
 24  DT_TRANSSM  404 non-null    float64
 25  DT_TRANSRM  0 non-null      float64
 26  DT_TRANSRS  0 non-null      float64
 27  DT_TRANSSE  37 non-null     float64
 28  CS_FLXRET   0 non-null      float64
 29  FLXRECEBI   0 non-null      float64
 30  MIGRADO_W   116 non-null    float64
 31  ID_OCUPA_N  70 non-null     float64
 32  TRATAMENTO  595 non-null    int64
 33  INSTITUCIO  116 non-null    float64
 34  RAIOX_TORA  587 non-null    float64
 35  TESTE_TUBE  116 non-null    float64
 36  FORMA       595 non-null    float64
 37  EXTRAPU1_N  531 non-null    object
 38  EXTRAPU2_N  116 non-null    float64
 39  EXTRAPUL_O  0 non-null      float64
 40  AGRAVAIDS   590 non-null    float64
 41  AGRAVALCOO  593 non-null    float64
 42  AGRAVDIABE  593 non-null    float64
 43  AGRAVDOENC  593 non-null    float64
 44  AGRAVOUTRA  541 non-null    float64
 45  AGRAVOUTDE  28 non-null     object
 46  BACILOSC_E  595 non-null    float64
 47  BACILOS_E2  116 non-null    float64
 48  BACILOSC_O  116 non-null    float64
 49  CULTURA_ES  595 non-null    float64
 50  CULTURA_OU  116 non-null    float64
 51  HIV         595 non-null    float64
 52  HISTOPATOL  592 non-null    float64
 53  DT_INIC_TR  589 non-null    float64
 54  RIFAMPICIN  116 non-null    float64
 55  ISONIAZIDA  116 non-null    float64
 56  ETAMBUTOL   116 non-null    float64
 57  ESTREPTOMI  116 non-null    float64
 58  PIRAZINAMI  116 non-null    float64
 59  ETIONAMIDA  116 non-null    float64
 60  OUTRAS      116 non-null    float64
 61  OUTRAS_DES  70 non-null     float64
 62  TRAT_SUPER  116 non-null    float64
 63  NU_CONTATO  594 non-null    float64
 64  DOENCA_TRA  116 non-null    float64
 65  SG_UF_AT    594 non-null    float64
 66  ID_MUNIC_A  594 non-null    float64
 67  DT_NOTI_AT  594 non-null    float64
 68  SG_UF_2     589 non-null    float64
 69  ID_MUNIC_2  582 non-null    float64
 70  BACILOSC_1  585 non-null    float64
 71  BACILOSC_2  582 non-null    float64
 72  BACILOSC_3  582 non-null    float64
 73  BACILOSC_4  575 non-null    float64
 74  BACILOSC_5  575 non-null    float64
 75  BACILOSC_6  575 non-null    float64
 76  TRATSUP_AT  586 non-null    float64
 77  DT_MUDANCA  116 non-null    float64
 78  NU_COMU_EX  587 non-null    float64
 79  SITUA_9_M   116 non-null    float64
 80  SITUA_12_M  33 non-null     float64
 81  SITUA_ENCE  584 non-null    float64
 82  DT_ENCERRA  578 non-null    float64
 83  TPUNINOT    531 non-null    float64
 84  POP_LIBER   595 non-null    float64
 85  POP_RUA     595 non-null    float64
 86  POP_SAUDE   595 non-null    float64
 87  POP_IMIG    595 non-null    float64
 88  BENEF_GOV   591 non-null    float64
 89  AGRAVDROGA  591 non-null    float64
 90  AGRAVTABAC  593 non-null    float64
 91  TEST_MOLEC  595 non-null    float64
 92  TEST_SENSI  436 non-null    float64
 93  ANT_RETRO   360 non-null    float64
 94  BAC_APOS_6  463 non-null    float64
 95  TRANSF      175 non-null    float64
 96  UF_TRANSF   58 non-null     float64
 97  MUN_TRANSF  52 non-null     float64
 98  ano         595 non-null    int64
dtypes: float64(84), int64(10), object(5)
memory usage: 460.3+ KB

In [117]:
df.head()

,Unnamed: 0,TP_NOT,ID_AGRAVO,DT_NOTIFIC,NU_ANO,SG_UF_NOT,ID_MUNICIP,ID_REGIONA,DT_DIAG,ANO_NASC,...,AGRAVDROGA,AGRAVTABAC,TEST_MOLEC,TEST_SENSI,ANT_RETRO,BAC_APOS_6,TRANSF,UF_TRANSF,MUN_TRANSF,ano
0,1198,2,A169,2015-05-15,2015,17,170210,0.0,20150515,1976.0,...,9.0,9.0,1.0,7.0,2.0,0.0,0.0,NaN,NaN,2015
1,1843,2,A169,2015-05-20,2015,17,170210,0.0,20150520,1949.0,...,0.0,1.0,1.0,7.0,2.0,0.0,0.0,NaN,NaN,2015
2,2776,2,A169,2015-05-26,2015,17,170210,0.0,20150526,1969.0,...,0.0,0.0,1.0,7.0,2.0,0.0,0.0,NaN,NaN,2015
3,4369,2,A169,2015-06-09,2015,17,172100,0.0,20150608,1969.0,...,0.0,0.0,1.0,5.0,0.0,0.0,1.0,NaN,NaN,2015
4,4981,2,A169,2015-06-12,2015,17,170930,0.0,20150611,1986.0,...,0.0,0.0,1.0,7.0,0.0,0.0,0.0,NaN,NaN,2015

In [118]:
df.shape

(595, 99)

#2- Pré-processamento

---

In [119]:
#Filtrando o dataset

In [120]:
#Filtrando seu DataFrame df para manter apenas as linhas onde a coluna 'SITUA_ENCE' contém os valores 1, 2, 3 ou 10.
df = df[df['SITUA_ENCE'].isin([1,2,3,10])]
#cura, obito por TB, abandono e abandono primário, falencia

In [121]:
df['SITUA_ENCE'].value_counts (normalize=False)

SITUA_ENCE
1.0     446
2.0      48
3.0      19
10.0      1
Name: count, dtype: int64

In [122]:
# Filtrando anos do estudo
df = df[df['NU_ANO'].isin([2015, 2016, 2017, 2018, 2019,2020, 2021,2022,2023,2024])]

In [123]:
df['TEST_MOLEC'].value_counts(dropna=False)

TEST_MOLEC
1.0    497
5.0     15
3.0      2
Name: count, dtype: int64

In [124]:
df = df[(df['TEST_SENSI'] == 5) | (df['TEST_MOLEC'] == 1)]

In [125]:
df.shape

(514, 99)

In [126]:
#Exclusao inicial de colunas

In [127]:
df.columns

Index(['Unnamed: 0', 'TP_NOT', 'ID_AGRAVO', 'DT_NOTIFIC', 'NU_ANO',
       'SG_UF_NOT', 'ID_MUNICIP', 'ID_REGIONA', 'DT_DIAG', 'ANO_NASC',
       'NU_IDADE_N', 'CS_SEXO', 'CS_GESTANT', 'CS_RACA', 'CS_ESCOL_N', 'SG_UF',
       'ID_MN_RESI', 'ID_RG_RESI', 'ID_PAIS', 'NDUPLIC_N', 'IN_VINCULA',
       'DT_DIGITA', 'DT_TRANSUS', 'DT_TRANSDM', 'DT_TRANSSM', 'DT_TRANSRM',
       'DT_TRANSRS', 'DT_TRANSSE', 'CS_FLXRET', 'FLXRECEBI', 'MIGRADO_W',
       'ID_OCUPA_N', 'TRATAMENTO', 'INSTITUCIO', 'RAIOX_TORA', 'TESTE_TUBE',
       'FORMA', 'EXTRAPU1_N', 'EXTRAPU2_N', 'EXTRAPUL_O', 'AGRAVAIDS',
       'AGRAVALCOO', 'AGRAVDIABE', 'AGRAVDOENC', 'AGRAVOUTRA', 'AGRAVOUTDE',
       'BACILOSC_E', 'BACILOS_E2', 'BACILOSC_O', 'CULTURA_ES', 'CULTURA_OU',
       'HIV', 'HISTOPATOL', 'DT_INIC_TR', 'RIFAMPICIN', 'ISONIAZIDA',
       'ETAMBUTOL', 'ESTREPTOMI', 'PIRAZINAMI', 'ETIONAMIDA', 'OUTRAS',
       'OUTRAS_DES', 'TRAT_SUPER', 'NU_CONTATO', 'DOENCA_TRA', 'SG_UF_AT',
       'ID_MUNIC_A', 'DT_NOTI_AT', 'SG_UF_2', 'ID_MUNIC_2', 'BACILOSC_1',
       'BACILOSC_2', 'BACILOSC_3', 'BACILOSC_4', 'BACILOSC_5', 'BACILOSC_6',
       'TRATSUP_AT', 'DT_MUDANCA', 'NU_COMU_EX', 'SITUA_9_M', 'SITUA_12_M',
       'SITUA_ENCE', 'DT_ENCERRA', 'TPUNINOT', 'POP_LIBER', 'POP_RUA',
       'POP_SAUDE', 'POP_IMIG', 'BENEF_GOV', 'AGRAVDROGA', 'AGRAVTABAC',
       'TEST_MOLEC', 'TEST_SENSI', 'ANT_RETRO', 'BAC_APOS_6', 'TRANSF',
       'UF_TRANSF', 'MUN_TRANSF', 'ano'],
      dtype='object')

In [128]:
df= (df>>
               drop('Unnamed: 0', 'TP_NOT', 'ID_AGRAVO','POP_SAUDE',
       'SG_UF_NOT', 'ID_MUNICIP', 'ID_REGIONA','ANO_NASC',
       'CS_GESTANT', 'SG_UF','DT_DIGITA','HISTOPATOL',
       'ID_RG_RESI', 'ID_PAIS', 'NDUPLIC_N', 'IN_VINCULA',
       'DT_TRANSUS', 'DT_TRANSDM', 'DT_TRANSSM', 'DT_TRANSRM',
       'DT_TRANSRS', 'DT_TRANSSE', 'CS_FLXRET', 'FLXRECEBI', 'MIGRADO_W',
       'ID_OCUPA_N', 'INSTITUCIO','TESTE_TUBE',
       'EXTRAPU1_N', 'EXTRAPU2_N', 'EXTRAPUL_O', 'AGRAVOUTRA', 'AGRAVOUTDE',
       'HIV', 'RIFAMPICIN', 'ISONIAZIDA',
       'ETAMBUTOL', 'ESTREPTOMI', 'PIRAZINAMI', 'ETIONAMIDA', 'OUTRAS',
       'OUTRAS_DES', 'DOENCA_TRA', 'SG_UF_AT',
       'ID_MUNIC_A', 'DT_NOTI_AT', 'SG_UF_2', 'ID_MUNIC_2',
       'BACILOSC_3',  'BACILOSC_5','BACILOSC_1',
       'TRAT_SUPER', 'CULTURA_OU',
       'BACILOSC_6','BAC_APOS_6','BACILOS_E2', 'BACILOSC_O',
       'DT_MUDANCA', 'NU_COMU_EX', 'SITUA_9_M', 'SITUA_12_M',
       'ANT_RETRO',  'TRANSF','TPUNINOT',
       'UF_TRANSF', 'MUN_TRANSF','AGRAVAIDS'
)
              )

Populacao

In [129]:
df['ID_MN_RESI'].value_counts(dropna=False)

ID_MN_RESI
172100    122
170210     95
170950     56
170550     25
171610     20
         ...
171845      1
170380      1
171215      1
171090      1
170384      1
Name: count, Length: 80, dtype: int64

In [130]:
df_pop = pd.read_csv('popTO.csv',sep=';',encoding='latin1')

In [131]:
df_pop.head()

       cod                       nome   pop
0  1700251           Abreulândia (TO)  2576
1  1700301         Aguiarnópolis (TO)  4497
2  1700350  Aliança do Tocantins (TO)  5147
3  1700400                 Almas (TO)  6499
4  1700707              Alvorada (TO)  8802

In [132]:
df_pop['ID_MN_RESI'] = df_pop['cod'].astype(str).str[:-1].astype(int)

In [133]:
df.shape

(514, 32)

In [134]:
df = df.merge(df_pop[['ID_MN_RESI', 'pop']], on='ID_MN_RESI', how='left')

In [135]:
df.shape

(514, 33)

Acrescentando variável front

In [136]:
df['ID_MN_RESI'].unique()

array([170210, 170825, 170710, 172100, 172015, 171660, 170510, 170300,
       172208, 170950, 171889, 170900, 171610, 172097, 170386, 172210,
       170980, 170560, 170930, 171430, 171360, 170820, 171200, 172090,
       170025, 171780, 170550, 171820, 170190, 172065, 171630, 170230,
       170310, 171500, 171180, 170730, 171050, 170650, 170555, 171380,
       170700, 171320, 171190, 172120, 171700, 171665, 170070, 170130,
       171330, 170255, 170240, 171830, 171420, 171570, 170330, 170215,
       170100, 170720, 170625, 171750, 170035, 171650, 171195, 171620,
       171488, 170307, 171525, 171880, 171150, 170830, 170390, 170388,
       171790, 170765, 171280, 171845, 170380, 171215, 171090, 170384])

In [137]:
##############Ajuste dos dados#########################

In [138]:
# Criando a variável 'cura' baseada na coluna 'SITUA_ENCE'
df['cura'] = df['SITUA_ENCE'].apply(lambda x: 1 if x == 1 else 0)

In [139]:
df['SITUA_ENCE'].value_counts(normalize=False)

SITUA_ENCE
1.0     446
2.0      48
3.0      19
10.0      1
Name: count, dtype: int64

In [140]:
df[df['SITUA_ENCE'] > 1]['SITUA_ENCE'].value_counts(normalize=False)

SITUA_ENCE
2.0     48
3.0     19
10.0     1
Name: count, dtype: int64

In [141]:
df[df['SITUA_ENCE'] > 1]['SITUA_ENCE'].value_counts(normalize=True)

SITUA_ENCE
2.0     0.705882
3.0     0.279412
10.0    0.014706
Name: proportion, dtype: float64

In [142]:
#TRABALHAR COM AS DATAS

# Selecionando as colunas específicas
df_selecionado = df[['DT_NOTIFIC', 'DT_DIAG', 'DT_INIC_TR', 'DT_ENCERRA']]

# Verificando o formato (tipo) das variáveis (colunas)
print(df_selecionado.dtypes)

# Convertendo as colunas para o formato datetime
df_selecionado['DT_DIAG'] = pd.to_datetime(df_selecionado['DT_DIAG'], format='%Y%m%d')
df_selecionado['DT_INIC_TR'] = pd.to_datetime(df_selecionado['DT_INIC_TR'], format='%Y%m%d')

# Verificando o novo formato das variáveis
print(df_selecionado.dtypes)

df_selecionado['DT_ENCERRA2'] = pd.to_datetime(
    df_selecionado['DT_ENCERRA'],
    format='%Y%m%d',
    errors='coerce'  # Trata erros e define valores inválidos como NaT
)

# Definindo como NaT as datas anteriores a 2000
df_selecionado['DT_ENCERRA2'] = df_selecionado['DT_ENCERRA2'].apply(
    lambda x: pd.NaT if x and x.year < 2000 else x
)

# Calculando a diferença em dias entre 'DT_DIAG' e 'DT_INIC_TR'
df_selecionado['TEMPO_DIAG_TRAT'] = (df_selecionado['DT_INIC_TR'] - df_selecionado['DT_DIAG']).dt.days
df_selecionado['TEMPO_TRAT_ENC'] = (df_selecionado['DT_ENCERRA2'] - df_selecionado['DT_INIC_TR']).dt.days
df_selecionado['TEMPO_DIAG_ENC'] = (df_selecionado['DT_ENCERRA2'] - df_selecionado['DT_DIAG']).dt.days

import numpy as np

# Condição para substituir 'TEMPO_TRAT_OBITO' por NaN quando for igual a 'TEMPO_DIAG_OBITO' e o valor for negativo
df_selecionado['TEMPO_TRAT_ENC'] = np.where(
    (df_selecionado['TEMPO_TRAT_ENC'] < 0),
    0,  # Substitui por NaN
    df_selecionado['TEMPO_TRAT_ENC']  # Caso contrário, mantém o valor original
)

# Convertendo as colunas para o formato datetime
df['DT_DIAG'] = pd.to_datetime(df['DT_DIAG'], format='%Y%m%d')
df['DT_INIC_TR'] = pd.to_datetime(df['DT_INIC_TR'], format='%Y%m%d')


# Criando uma nova coluna DT_ENCERRA2, convertendo a coluna DT_ENCERRA para datetime
df['DT_ENCERRA'] = pd.to_datetime(
    df['DT_ENCERRA'],
    format='%Y%m%d',
    errors='coerce'  # Trata erros e define valores inválidos como NaT
)

# Definindo como NaT as datas anteriores a 2000
df['DT_ENCERRA'] = df['DT_ENCERRA'].apply(
    lambda x: pd.NaT if x and x.year < 2000 else x
)

# Calculando a diferença em dias entre 'DT_DIAG' e 'DT_INIC_TR'
df['TEMPO_DIAG_TRAT'] = (df['DT_INIC_TR'] - df['DT_DIAG']).dt.days

# Calculando a diferença em dias entre 'DT_ENCERRA2' e 'DT_INIC_TR'
df['TEMPO_TRAT_ENC'] = (df['DT_ENCERRA'] - df['DT_INIC_TR']).dt.days

# Calculando a diferença em dias entre 'DT_ENCERRA2' e 'DT_DIAG'
df['TEMPO_DIAG_ENC'] = (df['DT_ENCERRA'] - df['DT_DIAG']).dt.days

# Condição para substituir 'TEMPO_TRAT_ENC' por NaN quando for igual a 'TEMPO_DIAG_ENC' e o valor for negativo
df['TEMPO_TRAT_ENC'] = np.where(
    (df['TEMPO_TRAT_ENC'] < 0),
    0,  # Substitui por NaN
    df['TEMPO_TRAT_ENC']  # Caso contrário, mantém o valor original
)

DT_NOTIFIC     object
DT_DIAG         int64
DT_INIC_TR    float64
DT_ENCERRA    float64
dtype: object
DT_NOTIFIC            object
DT_DIAG       datetime64[ns]
DT_INIC_TR    datetime64[ns]
DT_ENCERRA           float64
dtype: object

/tmp/ipykernel_7284/3504296559.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_selecionado['DT_DIAG'] = pd.to_datetime(df_selecionado['DT_DIAG'], format='%Y%m%d')
/tmp/ipykernel_7284/3504296559.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_selecionado['DT_INIC_TR'] = pd.to_datetime(df_selecionado['DT_INIC_TR'], format='%Y%m%d')
/tmp/ipykernel_7284/3504296559.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_selecionado['DT_ENCERRA2'] = pd.to_datetime(
/tmp/ipykernel_7284/3504296559.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_selecionado['DT_ENCERRA2'] = df_selecionado['DT_ENCERRA2'].apply(
/tmp/ipykernel_7284/3504296559.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_selecionado['TEMPO_DIAG_TRAT'] = (df_selecionado['DT_INIC_TR'] - df_selecionado['DT_DIAG']).dt.days
/tmp/ipykernel_7284/3504296559.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_selecionado['TEMPO_TRAT_ENC'] = (df_selecionado['DT_ENCERRA2'] - df_selecionado['DT_INIC_TR']).dt.days
/tmp/ipykernel_7284/3504296559.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_selecionado['TEMPO_DIAG_ENC'] = (df_selecionado['DT_ENCERRA2'] - df_selecionado['DT_DIAG']).dt.days
/tmp/ipykernel_7284/3504296559.py:35: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_selecionado['TEMPO_TRAT_ENC'] = np.where(

In [143]:
df['TEMPO_DIAG_TRAT'] = df['TEMPO_DIAG_TRAT'].clip(lower=0)
#substituir todos os valores menores que 0 por 0.

In [144]:
#TRABALHAR COM A IDADE

print(df['NU_IDADE_N'].unique())

[4038. 4066. 4046. 4028. 4032. 4047. 4053. 4044. 4017. 4060. 4078. 4051.
 4025. 4048. 4027. 4036. 4033. 4040. 4050. 4035. 4026. 4079. 4029. 4031.
 4043. 4063. 4056. 4041. 4062. 4037. 4023. 4016. 4068. 4019. 4021. 4042.
 4067. 4058. 4049. 4071. 4054. 4022. 4074. 4030. 4045. 4061. 4069. 4086.
 4059. 4072. 4057. 4034. 4081. 4039. 4084. 4014. 4024. 4055. 4018. 4020.
 4076. 4065. 4080. 4075. 4082. 2000. 4083. 4015. 4070. 4013. 4064. 2017.
 4077. 4011. 4073. 4085. 4093. 4005. 4052. 4008.]

In [145]:
import numpy as np

df['NU_IDADE_N'] = df['NU_IDADE_N'].replace(0, np.nan)

In [146]:
df['NU_IDADE_N'].isna().sum()

np.int64(0)

In [147]:
#TRABALHAR COM A IDADE

# Criando a variável tipo_idade (primeiro dígito)
import numpy as np

# Aplica a transformação somente onde a idade não é nula
df['tipo_idade'] = df['NU_IDADE_N'].apply(lambda x: str(int(x))[0] if pd.notna(x) else np.nan)


# Tabela de frequência de tipo_idade
print(df['tipo_idade'].value_counts())

tipo_idade
4    511
2      3
Name: count, dtype: int64

In [148]:
valores_com_1 = df['NU_IDADE_N'].dropna().astype(str)
valores_com_1 = valores_com_1[valores_com_1.str.startswith('1')]
print(valores_com_1.unique())

[]

In [149]:
import numpy as np

df['idade'] = df['NU_IDADE_N'].apply(
    lambda x: int(str(int(x))[2:]) if pd.notna(x) else np.nan
).astype('Int64')  # Int64 permite valores nulos

In [150]:
df['idade'] = df['NU_IDADE_N'].astype(str).str[2:]

In [151]:
df['idade'] = df['idade'].where(df['tipo_idade'] == "4", 0)

In [152]:
# Converte para tipo inteiro que aceita nulos
df['idade'] = pd.to_numeric(df['idade'], errors='coerce').astype('Int64')

In [153]:
df.loc[df['NU_IDADE_N'].isna(), 'idade'] = pd.NA

In [154]:
print(df['idade'].unique())

<IntegerArray>
[38, 66, 46, 28, 32, 47, 53, 44, 17, 60, 78, 51, 25, 48, 27, 36, 33, 40, 50,
 35, 26, 79, 29, 31, 43, 63, 56, 41, 62, 37, 23, 16, 68, 19, 21, 42, 67, 58,
 49, 71, 54, 22, 74, 30, 45, 61, 69, 86, 59, 72, 57, 34, 81, 39, 84, 14, 24,
 55, 18, 20, 76, 65, 80, 75, 82,  0, 83, 15, 70, 13, 64, 77, 11, 73, 85, 93,
  5, 52,  8]
Length: 79, dtype: Int64

In [155]:
# Exibindo a descrição estatística da coluna 'idade' do DataFrame
print(df['idade'].describe())

count        514.0
mean     42.661479
std      18.183551
min            0.0
25%           28.0
50%           40.0
75%           56.0
max           93.0
Name: idade, dtype: Float64

In [156]:
df['idade'].isna().sum()

np.int64(0)

In [157]:
df['faixa_etaria2'] = np.select(
    [
        df['idade'].astype(float) < 20,
        (df['idade'].astype(float) >= 20) & (df['idade'].astype(float) < 40),
        (df['idade'].astype(float) >= 40) & (df['idade'].astype(float) < 60),
        df['idade'].astype(float) >= 60
    ],
    [0, 1, 2, 3],
    default=np.nan
)

In [158]:
df['faixa_etaria2'].value_counts(dropna=False)

faixa_etaria2
1.0    213
2.0    158
3.0    106
0.0     37
Name: count, dtype: int64

In [159]:
df['CULTURA_ES'].value_counts(dropna=False)

CULTURA_ES
4.0    317
1.0    159
2.0     35
3.0      3
Name: count, dtype: int64

In [160]:
#modificando valores de variaveis
cols = ['CULTURA_ES', 'BACILOSC_E','BACILOSC_2','BACILOSC_4','RAIOX_TORA',]
for col in cols:
    df.loc[df[col] > 2, col] = np.nan

for col in cols:
    df.loc[df[col] == 0, col] = np.nan
#substituindo os valores 0 por NaN (valor ausente)

In [161]:
df['TRATSUP_AT'].value_counts(dropna=False)

TRATSUP_AT
1.0    325
0.0    178
9.0      8
NaN      3
Name: count, dtype: int64

In [162]:
# Lista das colunas a serem modificadas
#cols_to_replace = [
#    'RAIOX_TORA', 'AGRAVALCOO', 'AGRAVDIABE', 'AGRAVDOENC', 'POP_LIBER',
#    'POP_RUA', 'POP_IMIG', 'BENEF_GOV', 'AGRAVDROGA', 'AGRAVTABAC'
#]

# Substituir 2 por 1 nas colunas selecionadas
#df[cols_to_replace] = df[cols_to_replace].replace(2, 0)

# Substituir 2 por 1 nas colunas selecionadas
df['CULTURA_ES'] = df['CULTURA_ES'].replace(2, 0)
df['BACILOSC_E'] = df['BACILOSC_E'].replace(2, 0)
df['BACILOSC_2'] = df['BACILOSC_2'].replace(2, 0)
df['BACILOSC_4'] = df['BACILOSC_4'].replace(2, 0)
df['POP_LIBER'] = df['POP_LIBER'].replace(2, 0)
df['POP_RUA'] = df['POP_RUA'].replace(2, 0)
df['POP_IMIG'] = df['POP_IMIG'].replace(2, 0)
df['BENEF_GOV'] = df['BENEF_GOV'].replace(2, 0)
df['AGRAVDIABE'] = df['AGRAVDIABE'].replace(2, 0)
df['AGRAVDOENC'] = df['AGRAVDOENC'].replace(2, 0)
df['AGRAVALCOO'] = df['AGRAVALCOO'].replace(2, 0)
df['AGRAVDROGA'] = df['AGRAVDROGA'].replace(2, 0)
df['AGRAVTABAC'] = df['AGRAVTABAC'].replace(2, 0)
df['RAIOX_TORA'] = df['RAIOX_TORA'].replace(2, 0)
df['CS_SEXO'] = df['CS_SEXO'].replace('F', 0)
df['CS_SEXO'] = df['CS_SEXO'].replace('M', 1)

/tmp/ipykernel_7284/921383378.py:26: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['CS_SEXO'] = df['CS_SEXO'].replace('M', 1)

In [163]:
df['NU_CONTATO'].value_counts(dropna=False)

NU_CONTATO
1.0     101
2.0     100
3.0      81
4.0      67
0.0      57
5.0      26
7.0      25
6.0      20
10.0      8
15.0      6
8.0       5
13.0      4
9.0       3
16.0      3
14.0      2
23.0      1
17.0      1
12.0      1
95.0      1
11.0      1
35.0      1
Name: count, dtype: int64

In [164]:
df[df['NU_CONTATO'] > 20]['NU_CONTATO'].value_counts(dropna=False).sort_index()

NU_CONTATO
23.0    1
35.0    1
95.0    1
Name: count, dtype: int64

In [165]:
print(df['NU_CONTATO'].describe())

df['NU_CONTATO'].value_counts()

import numpy as np

df.loc[df['NU_CONTATO'] > 18, 'NU_CONTATO'] = np.nan

count    514.000000
mean       3.492218
std        5.318413
min        0.000000
25%        1.000000
50%        2.000000
75%        4.000000
max       95.000000
Name: NU_CONTATO, dtype: float64

In [166]:
import numpy as np

df['CONTATO_maior5'] = np.where(df['NU_CONTATO'].isna(), np.nan,
                                      (df['NU_CONTATO'] > 5).astype(int))


df['CONTATO_maior5'].value_counts(dropna=False)

CONTATO_maior5
0.0    432
1.0     79
NaN      3
Name: count, dtype: int64

In [167]:
df['CS_ESCOL_N'].value_counts(dropna=False)
#9 = ignorado; # 10 = Nao se aplica

CS_ESCOL_N
6.0     85
3.0     83
1.0     77
5.0     58
0.0     52
4.0     50
9.0     42
2.0     28
8.0     16
NaN     10
7.0      9
10.0     4
Name: count, dtype: int64

0. Analfabeto,  1. 1ª a 4ª série incompleta do EF, 2. 4ª série completa do EF ( antigo 1° grau), 3. 5ª à 8ª série incompleta do EF (antigo ginásio ou 1° grau), 4. Ensino fundamental completo (antigo ginásio ou 1° grau), 5. Ensino médio incompleto (antigo colegial ou 2° grau), 6. Ensino médio completo (antigo colegial ou 2° grau), 7. Educação superior incompleta,  8. Educação superior completa,  9. Ignorado, 10. Não se aplica

In [168]:
# Criar a variável ESCOLA_FAIXA
df['ESCOLA_FAIXA'] = np.select(
    [
        df['CS_ESCOL_N'].between(0, 5, inclusive='both'),  # 0 a 5
        df['CS_ESCOL_N'].between(6, 8, inclusive='both'),  # 6 a 8
        df['CS_ESCOL_N'] == 10                             # não se aplica
    ],
    [0, 1, 10],
    default=np.nan  # mantém os valores ausentes
)

# Converter para inteiro com suporte a NaN
df['ESCOLA_FAIXA'] = df['ESCOLA_FAIXA'].astype('Int64')

In [169]:
df['ESCOLA_FAIXA'].value_counts(dropna=False)

ESCOLA_FAIXA
0       348
1       110
<NA>     52
10        4
Name: count, dtype: Int64

In [170]:
df[df['TEMPO_DIAG_TRAT'] > 14]['TEMPO_DIAG_TRAT'].value_counts(dropna=False)

TEMPO_DIAG_TRAT
35.0     4
17.0     4
21.0     4
16.0     3
28.0     3
44.0     2
31.0     2
49.0     2
18.0     2
63.0     2
15.0     2
19.0     2
61.0     2
25.0     2
50.0     1
154.0    1
94.0     1
59.0     1
204.0    1
103.0    1
116.0    1
86.0     1
67.0     1
46.0     1
72.0     1
33.0     1
169.0    1
30.0     1
62.0     1
140.0    1
20.0     1
43.0     1
81.0     1
173.0    1
37.0     1
285.0    1
92.0     1
195.0    1
Name: count, dtype: int64

In [171]:
df['TEMPO_DIAG_TRAT'].isna().sum()

np.int64(3)

In [172]:
# Criar variável binária mantendo valores ausentes
df['TEMPO_DIAG_TRAT_14'] = np.where(df['TEMPO_DIAG_TRAT'].isna(),
                                    np.nan,
                                    (df['TEMPO_DIAG_TRAT'] > 14).astype(int))

In [173]:
df['TEMPO_DIAG_TRAT_14'].value_counts(dropna=False)

TEMPO_DIAG_TRAT_14
0.0    451
1.0     60
NaN      3
Name: count, dtype: int64

In [174]:
df['POP_IMIG'].value_counts(dropna=False)

POP_IMIG
0.0    505
9.0      5
1.0      4
Name: count, dtype: int64

In [175]:
df['POP_IMIG'] = df['POP_IMIG'].replace(3, 9)

In [176]:
df['POP_IMIG'].value_counts(dropna=False)

POP_IMIG
0.0    505
9.0      5
1.0      4
Name: count, dtype: int64

In [177]:
df.columns

Index(['DT_NOTIFIC', 'NU_ANO', 'DT_DIAG', 'NU_IDADE_N', 'CS_SEXO', 'CS_RACA',
       'CS_ESCOL_N', 'ID_MN_RESI', 'TRATAMENTO', 'RAIOX_TORA', 'FORMA',
       'AGRAVALCOO', 'AGRAVDIABE', 'AGRAVDOENC', 'BACILOSC_E', 'CULTURA_ES',
       'DT_INIC_TR', 'NU_CONTATO', 'BACILOSC_2', 'BACILOSC_4', 'TRATSUP_AT',
       'SITUA_ENCE', 'DT_ENCERRA', 'POP_LIBER', 'POP_RUA', 'POP_IMIG',
       'BENEF_GOV', 'AGRAVDROGA', 'AGRAVTABAC', 'TEST_MOLEC', 'TEST_SENSI',
       'ano', 'pop', 'cura', 'TEMPO_DIAG_TRAT', 'TEMPO_TRAT_ENC',
       'TEMPO_DIAG_ENC', 'tipo_idade', 'idade', 'faixa_etaria2',
       'CONTATO_maior5', 'ESCOLA_FAIXA', 'TEMPO_DIAG_TRAT_14'],
      dtype='object')

In [178]:
# SEGUNDA EXCLUSAO DE VARIAVEIS

In [179]:
df= (df>>
               drop('NU_IDADE_N','tipo_idade','DT_NOTIFIC','DT_DIAG','DT_ENCERRA','DT_NOTIFIC','DT_INIC_TR','TEST_SENSI','TEST_MOLEC',
                     'TEMPO_DIAG_TRAT', 'TEMPO_TRAT_ENC','TEMPO_DIAG_ENC','CS_ESCOL_N','FORMA','TRATAMENTO','NU_CONTATO','idade',
                     'SITUA_ENCE','ano','ID_MN_RESI','BACILOSC_2','BACILOSC_4'
)
              )

##• Informações gerais da base (shape) (Obrigatório)

In [180]:
df.shape

(514, 22)

##• Verificação de valores ausentes (Obrigatório)

In [181]:
#Valores ausentes

In [182]:
# Verificar a presença de valores nulos
print(df.isnull().sum())

NU_ANO                  0
CS_SEXO                 0
CS_RACA                 0
RAIOX_TORA            162
AGRAVALCOO              1
AGRAVDIABE              2
AGRAVDOENC              2
BACILOSC_E             58
CULTURA_ES            320
TRATSUP_AT              3
POP_LIBER               0
POP_RUA                 0
POP_IMIG                0
BENEF_GOV               3
AGRAVDROGA              4
AGRAVTABAC              2
pop                     0
cura                    0
faixa_etaria2           0
CONTATO_maior5          3
ESCOLA_FAIXA           52
TEMPO_DIAG_TRAT_14      3
dtype: int64

In [183]:
# Get current columns after dropping some in previous steps
current_cols = df.columns

# Filter colunas to only include columns that still exist in df
cols_to_process = [col for col in current_cols if col in current_cols and col not in ['NU_ANO','pop']]

for col in cols_to_process:
    df[col] = df[col].replace(9, np.nan)


for col in cols_to_process:
    df[col] = df[col].replace(99, np.nan)

for col in cols_to_process:
    # Check if the column is of object type before replacing empty strings
    if df[col].dtype == 'object':
        df[col] = df[col].replace('', np.nan)

# Verificar a presença de valores nulos
print(df.isnull().sum())

# Print the list of columns being processed (optional, for debugging)
# print("Columns being processed:", cols_to_process)

NU_ANO                  0
CS_SEXO                 0
CS_RACA                10
RAIOX_TORA            162
AGRAVALCOO             11
AGRAVDIABE             11
AGRAVDOENC              8
BACILOSC_E             58
CULTURA_ES            320
TRATSUP_AT             11
POP_LIBER               4
POP_RUA                 7
POP_IMIG                5
BENEF_GOV              28
AGRAVDROGA             19
AGRAVTABAC             11
pop                     0
cura                    0
faixa_etaria2           0
CONTATO_maior5          3
ESCOLA_FAIXA           52
TEMPO_DIAG_TRAT_14      3
dtype: int64

In [184]:
df.columns

Index(['NU_ANO', 'CS_SEXO', 'CS_RACA', 'RAIOX_TORA', 'AGRAVALCOO',
       'AGRAVDIABE', 'AGRAVDOENC', 'BACILOSC_E', 'CULTURA_ES', 'TRATSUP_AT',
       'POP_LIBER', 'POP_RUA', 'POP_IMIG', 'BENEF_GOV', 'AGRAVDROGA',
       'AGRAVTABAC', 'pop', 'cura', 'faixa_etaria2', 'CONTATO_maior5',
       'ESCOLA_FAIXA', 'TEMPO_DIAG_TRAT_14'],
      dtype='object')

In [185]:
#Converter o desfecho em variável numérica
df.cura = df.cura.astype('Int64')

#Visualização dos novos tipos
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 514 entries, 0 to 513
Data columns (total 22 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   NU_ANO              514 non-null    int64
 1   CS_SEXO             514 non-null    int64
 2   CS_RACA             504 non-null    float64
 3   RAIOX_TORA          352 non-null    float64
 4   AGRAVALCOO          503 non-null    float64
 5   AGRAVDIABE          503 non-null    float64
 6   AGRAVDOENC          506 non-null    float64
 7   BACILOSC_E          456 non-null    float64
 8   CULTURA_ES          194 non-null    float64
 9   TRATSUP_AT          503 non-null    float64
 10  POP_LIBER           510 non-null    float64
 11  POP_RUA             507 non-null    float64
 12  POP_IMIG            509 non-null    float64
 13  BENEF_GOV           486 non-null    float64
 14  AGRAVDROGA          495 non-null    float64
 15  AGRAVTABAC          503 non-null    float64
 16  pop                 514 non-null    int64
 17  cura                514 non-null    Int64
 18  faixa_etaria2       514 non-null    float64
 19  CONTATO_maior5      511 non-null    float64
 20  ESCOLA_FAIXA        462 non-null    Int64
 21  TEMPO_DIAG_TRAT_14  511 non-null    float64
dtypes: Int64(2), float64(17), int64(3)
memory usage: 89.5 KB

In [186]:
#converter todas as colunas para letras minusculas
df.columns = df.columns.str.lower()

#verificar novas colunas
df.columns

Index(['nu_ano', 'cs_sexo', 'cs_raca', 'raiox_tora', 'agravalcoo',
       'agravdiabe', 'agravdoenc', 'bacilosc_e', 'cultura_es', 'tratsup_at',
       'pop_liber', 'pop_rua', 'pop_imig', 'benef_gov', 'agravdroga',
       'agravtabac', 'pop', 'cura', 'faixa_etaria2', 'contato_maior5',
       'escola_faixa', 'tempo_diag_trat_14'],
      dtype='object')

In [187]:
df.shape

(514, 22)

In [188]:
df.to_csv("dadosTO_entregavel_1_2015_2024.csv", index=False)