#Tocantins

#->   Lendo banco de dados

In [ ]:
import pandas as pd

In [ ]:
from os import read
df  = pd.read_csv("dadosTO_entregavel_1_2015_2024.csv")

In [ ]:
df.shape

(3851, 24)

In [ ]:
df.columuns

In [ ]:
df = df.drop(columns=['bacilosc_2','bacilosc_4'])

##• Separação da base em treino e teste (Obrigatório)

In [ ]:
# Selecao treino e teste

In [ ]:
# Separação da base entre variáveis preditoras e desfecho
X = df.drop(columns="cura")
y = df["cura"].copy()

# Separação entre treino (NU_ANO ≠ 2023) e teste (NU_ANO == 2023)
X_train = X[X['nu_ano'] < 2023].drop(columns="nu_ano").copy()
X_test  = X[X['nu_ano'] > 2022].drop(columns="nu_ano").copy()

y_train = y[X['nu_ano'] < 2023].copy()
y_test  = y[X['nu_ano'] > 2022].copy()

In [ ]:
print("Proporção das classes no conjunto de TREINO:")
print(y_train.value_counts(normalize=True))

print("\nProporção das classes no conjunto de TESTE:")
print(y_test.value_counts(normalize=True))

Proporção das classes no conjunto de TREINO:
cura
1    0.865783
0    0.134217
Name: proportion, dtype: float64

Proporção das classes no conjunto de TESTE:
cura
1    0.855727
0    0.144273
Name: proportion, dtype: float64

In [ ]:
def visualizar_dataframe(df, nome_df):
  '''Função que dá o shape do dataframe e fornece as 5 primeiras linhas'''

  #Fornece o shape da tabela
  print(f"Shape {nome_df}: ", df.shape)

  #Visualiza as 5 primeiras linhas do DataFrame
  display(df.head())

##• Proporção do desfecho (Obrigatório)

In [ ]:
#Verificação da proporção de abandono na base de treino e teste
display(y_train.value_counts(normalize = True))
display(y_test.value_counts(normalize = True))

cura
1    0.865783
0    0.134217
Name: proportion, dtype: float64

cura
1    0.855727
0    0.144273
Name: proportion, dtype: float64

##• Tratamento de valores ausentes numéricos (Obrigatório)

## Imputação dos Valores Ausentes (Missing Values)

In [ ]:
#Verificação de valores ausentes na base:
print("Quantidade de missings no treino: ", X_train.isna().sum().sum())
print("Quantidade de missings no teste: ", X_test.isna().sum().sum())

Quantidade de missings no treino:  11926
Quantidade de missings no teste:  3236

In [ ]:
df.columns

Index(['nu_ano', 'cs_sexo', 'cs_raca', 'raiox_tora', 'agravalcoo',
       'agravdiabe', 'agravdoenc', 'bacilosc_e', 'cultura_es', 'bacilosc_2',
       'tratsup_at', 'pop_liber', 'pop_rua', 'pop_imig', 'benef_gov',
       'agravdroga', 'agravtabac', 'pop', 'front', 'cura', 'faixa_etaria2',
       'contato_maior5', 'escola_faixa', 'tempo_diag_trat_14'],
      dtype='object')

In [ ]:
#Lista de variáveis numéricas
lista_variaveis_numericas = ["pop"]

#Lista de variáveis categóricas( tirar pop e cura)
lista_variaveis_categoricas = [ 'cs_sexo', 'cs_raca', 'raiox_tora', 'agravalcoo',
       'agravdiabe', 'agravdoenc', 'bacilosc_e', 'cultura_es', 'bacilosc_2',
       'tratsup_at', 'pop_liber', 'pop_rua', 'pop_imig', 'benef_gov',
       'agravdroga', 'agravtabac', 'front', 'faixa_etaria2',
       'contato_maior5', 'escola_faixa', 'tempo_diag_trat_14']

In [ ]:
#Obtenção das médias na base de treino
median_treino = X_train[lista_variaveis_numericas].median()

#Aplicação das médias na base de treino e de teste
X_train[lista_variaveis_numericas] = X_train[lista_variaveis_numericas].fillna(median_treino)
X_test[lista_variaveis_numericas] = X_test[lista_variaveis_numericas].fillna(median_treino)

##

##• Tratamento de valores ausentes categóricos (Obrigatório)

In [ ]:
#Obtenção da moda nas bases de treino
#modas_treino = X_train[lista_variaveis_categoricas].mode().iloc[0]

#Criaçao de categoria ausente nas base de treino e de teste
X_train[lista_variaveis_categoricas] = X_train[lista_variaveis_categoricas].fillna(9)
X_test[lista_variaveis_categoricas] = X_test[lista_variaveis_categoricas].fillna(9)

In [ ]:
# categoria ausente ja foi criada
#df[lista_variaveis_categoricas].fillna("variavel_ausente", inplace = True)

In [ ]:
#Verificação de valores ausentes na base:
print("Quantidade de missings no treino: ", X_train.isna().sum().sum())
print("Quantidade de missings no teste: ", X_test.isna().sum().sum())

Quantidade de missings no treino:  0
Quantidade de missings no teste:  0

##• Padronização das variáveis numéricas (Obrigatório)

In [ ]:
# Padronizacao de variaveis numericas

In [ ]:
#Criação do Scaler
standard_scaler = StandardScaler()

#Treino do Scaler na base de treino
standard_scaler.fit(X_train[lista_variaveis_numericas])

StandardScaler()

In [ ]:
# Criação do DataFrame com valores originais e padronizados
df_pop = pd.DataFrame({
    'pop_original': X_train['pop'],
    'pop_padronizada': standard_scaler.transform(X_train[['pop']]).flatten()
})

# Exemplo: salvar em CSV
df_pop.to_csv('pop_padronizada.csv', index=False)

# Verifique o resultado
print(df_pop.head())

   pop_original  pop_padronizada
0       31942.0        -0.559417
1      252716.0        -0.140515
2      751300.0         0.805510
3       61146.0        -0.504005
4      751300.0         0.805510

In [ ]:
#Aplicação do Scaler na base de treino e de teste
X_train[lista_variaveis_numericas] = standard_scaler.transform(X_train[lista_variaveis_numericas])
X_test[lista_variaveis_numericas] = standard_scaler.transform(X_test[lista_variaveis_numericas])

##• Padronização das variáveis One Hot Encoding das categóricas (Obrigatório)

In [ ]:
# One Hot Encoding nas Variáveis Categóricas

In [ ]:
#cria o one hot encoder
one_hot_encoder = OneHotEncoder(drop = "if_binary", sparse_output = False,handle_unknown="ignore")

#treinar o one hot encoding na base de treino
one_hot_encoder.fit(X_train[lista_variaveis_categoricas])

#aplicar na base de treino e de teste
X_train_encoded = pd.DataFrame(one_hot_encoder.transform(X_train[lista_variaveis_categoricas]),
                               columns=one_hot_encoder.get_feature_names_out(),
                               index=X_train.index)

X_test_encoded = pd.DataFrame(one_hot_encoder.transform(X_test[lista_variaveis_categoricas]),
                              columns=one_hot_encoder.get_feature_names_out(),
                              index=X_test.index)

In [ ]:
##Deletando variaveis originais

In [ ]:
#Drop das features categóricas originais
X_train.drop(columns = lista_variaveis_categoricas, inplace = True)
X_test.drop(columns = lista_variaveis_categoricas, inplace = True)

#Junta as variáveis numéricas com as categóricas
X_train = pd.concat([X_train, X_train_encoded], axis=1)
X_test = pd.concat([X_test, X_test_encoded], axis=1)

In [ ]:
#Salvando dataframe

In [ ]:
#mount google colab
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import os

# Criar pasta se não existir
path_folder = "/content/drive/MyDrive/Colab Notebooks/ML_2026"
os.makedirs(path_folder, exist_ok=True)

In [ ]:
#Unificando base de Treino
df_train = pd.concat([X_train, y_train], axis = 1)

#Salvando base de Treino
path_to_save_train = "/content/drive/MyDrive/Colab Notebooks/ML_2026/dados_treino_processados2_to_2015_2024_aula.csv"
df_train.to_csv(path_to_save_train, index = False)

In [ ]:
#Unificando base de Teste
df_test= pd.concat([X_test, y_test], axis = 1)

#Salvando base de Teste
path_to_save_test = "/content/drive/MyDrive/Colab Notebooks/ML_2026/dados_teste_processados2_to_2015_2024_aula.csv"
df_test.to_csv(path_to_save_test, index = False)